name: Build in DevContainer
on:
  push:
  pull_request:

jobs:
  build:
    name: Build in DevContainer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: pnpm build
